In [1]:
import numpy as np
from numpy import linalg as LA  # Notar que importamos linalg con nickname LA

In [3]:
d = 3
c1 = 2*(np.random.rand(d,1)-0.5) # c1 y c2 son dos vectores 3x1 con elementos aleatorios en el 
c2 = 2*(np.random.rand(d,1)-0.5) # rango (-1,1). Pregunta: por que puedo sumar un vector
                                 # y un escalar?Buscar "numpy broadcasting"
print(np.dot(c1.T,c2)/(LA.norm(c1)*LA.norm(c2)))
# EL producto escalar entre c1 y c2 es c1.c2 = |c1||c2|cos(theta), entonces, 
# c1.c2/(|c1||c2|) = cos(theta), por lo que si este numero NO es 1 ni -1, sabemos que los
# vectores c1 y c2 no son linealmente independientes.
# Por otra parte, habiendo generado c1 y c2 al azar, las chances de que sean linealmente
# dependientes son minusculas. Igualmente vale la pena probar que no es 1.

[[-0.17965629]]


In [4]:
print("c1 = \n", c1)
print("c2 = \n", c2)

c1 = 
 [[ 0.87362597]
 [ 0.83531565]
 [-0.76604874]]
c2 = 
 [[ 0.14388371]
 [-0.09318158]
 [ 0.13589776]]


In [5]:
d1 = 2*(np.random.rand()-0.5) # d1 y d2 son escalares en el rango (-1,1)
d2 = 2*(np.random.rand()-0.5)
c3 = d1*c1 + d2*c2  # c3, por construccion, es linealmente dependiente de c1 y c2.
print("c1 = \n",c1)
print("c2 = \n",c2)
print("c3 = \n",c3) # Sin embargo eso NO es obvio a simple vista

c1 = 
 [[ 0.87362597]
 [ 0.83531565]
 [-0.76604874]]
c2 = 
 [[ 0.14388371]
 [-0.09318158]
 [ 0.13589776]]
c3 = 
 [[-0.66897236]
 [-0.52929443]
 [ 0.461283  ]]


Chequear en Geogebra 3D que c3 es linealmente dependiente de c1 y c2

In [6]:
A = np.concatenate((c1, c2, c3), axis=1) # construimos la matriz A con columnas c1, c2 y c3
print(A.shape)
print(A)  # chequear que, efectivamente, las columnas de A son c1, c2 y c3
LA.matrix_rank(A)  # EL rango de la matriz es el numero de columnas linealmente independientes

(3, 3)
[[ 0.87362597  0.14388371 -0.66897236]
 [ 0.83531565 -0.09318158 -0.52929443]
 [-0.76604874  0.13589776  0.461283  ]]


2

In [7]:
# Construimos explicitamente A de modo que una de sus 3 columnas es linealmente dependiente
# de las otras dos. Ahora hagamos de cuenta que no sabemos esto. Por cierto que, dado
# que generamos las componentes de manera aleatoria, la dependencia linal no es obvia
# a simple vista, pero por construccion sabemos que esta ahi.
#
# Entonces, recordemos:
# 1) c1 y c2 son linealmente independiente. 
# 2) c3 es linealmente Dependiente de {c1, c2}
# 3) Como los coeficientes fueron generados al azar, con probabilidad 0.99999999999.....
#    c3 es lineamente independiente de c1 y c2 como vectores individuales,
#    PERO ESTA EN EL PLANO GENERADO POR c1 y c2.
# 4) Por lo tanto, con altisima probabilidad, los pares {c1, c3} y {c2, c3} tambien
#    son linealmente idependientes (chequearlo en Geogebra!).
# 5) Sin embargo, la terna {c1, c2, c3} es linealmente dependiente. (comprobarlo en Geogebra)
# 6) Esto implica que el SPAN de {c1, c2, c3} es un plano, no es R^3.
#
# De ahora en mas, como dije mas arriba, hacemos de cuenta que
#
#            NO SABEMOS QUE LAS COLUMNAS DE A SON LINEALMENTE DEPENDIENTES!

In [8]:
np.linalg.det(A)  # Una manera automatica de chequear si las columnas son linealmente
                  # dependientes es calcular el determinante. Si da cero son linealmente
                  # dependients. Ver el video de determinantes de 3Blue1Brown y entender  
                  # el significado geometrico del determinante (como se
                  # transforman los volumenes) para entender por que si son lin dep el det
                  # tiene que ser cero.
            
                  # Pero, aunque el determinante de A sea cero, y por lo tanto no podamos
                  # calcular la inversa de A, el sistema A x = b puede
                  # tener solucion si justo b pertence al subespacio spanned por las columnas
                  # de A. Vamos a averiguarlo con el metodo de Gram-Schmidt

4.526876677282164e-19

In [9]:
# Como estamos jugando a que no sabemos como se construyo A, extraigamos los vectores columnas y,
# a travez del proceso de Gram-Schmidt, obtengamos con una base ortonormal
# del subespacio generado por el span de las columnas de A
c1A = A[:, [0]]  # columna 1 de la matriz A 
print(c1A.shape)
print(c1A)
c2A = A[:, [1]]  # columna 2 de la matriz A 
print(c2A.shape)
print(c2A)
c3A = A[:, [2]]  # columna 3 de la matriz A
print(c3A.shape)
print(c3A)

(3, 1)
[[ 0.87362597]
 [ 0.83531565]
 [-0.76604874]]
(3, 1)
[[ 0.14388371]
 [-0.09318158]
 [ 0.13589776]]
(3, 1)
[[-0.66897236]
 [-0.52929443]
 [ 0.461283  ]]


In [11]:
n1A = c1A/LA.norm(c1A)          # dividiendo al vector por su magnitud obtenemos un vector
                                # en la misma direccion pero de magnitud (o "norma") 1.
print(n1A)
print(np.dot(n1A.T,n1A))  # chequeamos que su norma es 1 multiplicandolo
                                      # escalarmente por si mismo

[[ 0.61049374]
 [ 0.58372231]
 [-0.53531828]]
[[1.]]


In [12]:
# Ya tenemos el vector n1A, que es proporcional a c1A, pero de magnitud 1.
# Ahora queremos construir el vector n2A.
# Recordedmos que n2A es tiene que ser ortonormal con n1A, y tal que el span de {n1A, n2A}
# sea el mismo que el de {c1A, c2A}
# El mecanismo es: 
# 1) calculamos la componente de c2A paralela a n1A, la llamamos P_c2A_n1A
P_c2A_n1A = np.dot(n1A.T,c2A)*n1A # la proyeccion del vector c2A sobre el vector n1A es
                                              # (c2A.n1A) n1A 
                                              # c2A.n1A es producto escalar de C2A por n1A,
                                              # que da la magnitud de la proyeccion de c2A 
                                              # sobre sobre n1A. Luego, al multiplicarlo por n1A,
                                              # el vector resultante apunta en la direccion de n1A
                                              # La formula general inluye una division por 
                                              # (n1A.n1A)
                                              # en este caso no es necesario porque (n1A.n1A) = 1
print(P_c2A_n1A)

[[-0.02399278]
 [-0.02294065]
 [ 0.02103834]]


In [13]:
# 2) Calculamos la componente de c2A perpendicular a n1A.
#    A dicha componente la llamamos P_c2A_perp_n1A (largo pero explicito... :))
# 2_a) Se calcula simplemente restandole a c2A la componente paralela a n1A que 
#      ya calculamos en el paso 1.
#      Naturalmente, P_c2A_perp_n1A tiene que ser perpendicular a n1A. 
P_c2A_perp_n1A = c2A - P_c2A_n1A  # la proyeccion del vector c2A perpendicular al vector n1A es
                                  # c2A - P_c2A_n1A
print(P_c2A_perp_n1A)
print(np.dot(P_c2A_perp_n1A.T,P_c2A_n1A)) # para chequear la perpendicularidad de
                                                      # P_c2A_perp_n1A y P_c2A_n1A
                                                      # calculamos su producto escalar

[[ 0.16787649]
 [-0.07024093]
 [ 0.11485942]]
[[0.]]


In [14]:
print(c2A)                          # Chequamos que c2A = P_c2A_n1A + P_c2A_perp_n1A de dos maneras
print(P_c2A_n1A + P_c2A_perp_n1A)   # 1- Observando numericamente si coinciden
c2A == P_c2A_n1A + P_c2A_perp_n1A   # 2- Preguntandole a Python con "=="
                                    # (ojo con este ultimo metodo porque puede llegar a dar
                                    # False por errores que las maquinas siempre cometen)

[[ 0.14388371]
 [-0.09318158]
 [ 0.13589776]]
[[ 0.14388371]
 [-0.09318158]
 [ 0.13589776]]


array([[ True],
       [ True],
       [ True]])

In [15]:
# 3) Calculamos n2A (que tiene que tener norma 1) simplemente dividiendo a 
#    P_c2A_perp_n1A por su norma.
# 3_a) Chequeamos que el conjunto {n1A, n2A} es ortonormal
#
n2A = P_c2A_perp_n1A/LA.norm(P_c2A_perp_n1A) # Generamos n2A, que es el vector de norma = 1
print(n2A)                                          # perpendicular a n1A 
print(np.dot(n2A.T,n2A))                # El conjunto {n1A, n2A} es ortonormal y
print(np.dot(n1A.T,n2A))                # genera el subespacio de R3 en el que "viven"
                                                    # c1A y c2A

[[ 0.78011247]
 [-0.32640559]
 [ 0.53374518]]
[[1.]]
[[-5.55111512e-17]]


Chequear en Geogebra 3D que n1A y n2A spanean el mismo plano que c1A y c2A pero son ortonormales 

In [16]:
# 4) Queremos calcular la componente de c3A perpendicular a n1A y n2A (y por lo tanto,
#    tambien perpendicular a c1A y c2A)
# 4_a) Primero calculamos las componentes de c3A paraleleas a n1A y n2A.

P_c3A_n1A = np.dot(n1A.T,c3A)*n1A # Continuamos con el proceso de Gram-Schmidt con
P_c3A_n2A = np.dot(n2A.T,c3A)*n2A # el vector c3A. Ahora estamos calculando las
print(P_c3A_n1A)                              # proyecciones de c3A sobre n1A y n2A
print(P_c3A_n2A)                              

[[-0.58869766]
 [-0.56288204]
 [ 0.51620615]]
[[-0.0802747 ]
 [ 0.03358761]
 [-0.05492315]]


In [17]:
# 4_b) Calculamos la componente de c3A perpendicular a n1A y n2A.
#      A esto lo hacemos simplemente restando de c3A las componentes paralelas a n1A y a n2A

P_c3A_perp_n1Ayn2A = c3A - P_c3A_n1A - P_c3A_n2A # Intentamos extraer la componente de c3A que
print(P_c3A_perp_n1Ayn2A)                        # NO esta en el subespacio spanned por 
                                                 # {n1A, n2A} pero nos da zero!
                                                 # Esto significa que c3A el linealmente
                                                 # dependiente de c1A y c2A 
                                                 #
                                                 # Por eso concluimos que el sistema
                                                 # A x = b
                                                 # solo tendra solucion si justo b pertenece
                                                 # al mismo subespacio.

[[-1.38777878e-17]
 [ 6.93889390e-18]
 [-2.08166817e-17]]


In [18]:
"""Ecuaciones lineales: A x = b"""
# Nuestro proposito es entender cuando la ecuacion A x = b va a tener solucion.
# Y que tipo de soluciones tiene
#
# Miremos el lado derecho de la ecuacion: A x
# Recordemos que A x, donde x es un vector 3x1 de coeficientes incognita,
# tiene el significado geometrico de una combinacion lineal de los vecores columna de A.
# Los coeficientes de esa combinacion son los componentes incognita de x.
# 
# Ahora miremos el lado izquierdo: b
# la unica manera de que la ecuacion A x = b tenga solucion es que b viva en el subespacio spanned
# por las columnas de A: C(A).
# Entonces, si generamos un b al azar, con probabilidad ~1 la ecuacion no va atener solucion:
b = 2*(np.random.rand(d,1)-0.5)
x = LA.solve(A, b)  
print(x)
# numericamente esto aparece como un vector gigante

[[-2.69442418e+17]
 [-1.87545085e+17]
 [-3.92208395e+17]]


In [22]:
# Chequeamos que, efectivamente, x NO es una solucion de la ecuacion A x = b, o de A x - b = 0
print(np.dot(A,x)-b)

[[0.12218788]
 [0.91224957]
 [0.05358135]]


In [19]:
# Supongamos entonces que b vive en el subespacio
# generado por las columnas de A. Como generamos un b asi?
# Asi:

bb1 = 2*(np.random.rand()-0.5) # bb1 y bb2 son escalares en el rango (-1,1)
bb2 = 2*(np.random.rand()-0.5)
b = bb1*n1A + bb2*n2A            # Por que puedo estar seguro de que esto vive en el subespacio
print(b)                       # generado por las columnas de A? Numericamente no resulta obvio.

[[ 0.16607921]
 [ 0.63332346]
 [-0.68453777]]


Chequear en Geogebra que b vive en el plano (subespacio generado por n1A y n2A)

In [20]:
x = LA.solve(A, b)                   # Asi resolvemos la ecuacion "singular", pero
                                     # todavia no entendemos conceptualmente como
                                     # encontrar esta solucion
print(x)

[[-21.06365068]
 [-17.08579679]
 [-31.43059489]]


In [21]:
# Chequeamos que, efectivamente, x es una solucion de la ecuacion A x = b, o de A x - b = 0
print(np.dot(A,x)-b)

[[-9.99200722e-16]
 [-1.33226763e-15]
 [ 1.77635684e-15]]


In [20]:
# Como vimos, si hubiera 2 soluciones distintas entre si, x1 y x2 , de la ecuacion
# A x = b, esto es, si A x1 = b y A x2 = b y x1 distinto de x2,
# Entonces A (x1 - x2) = 0, donde (x1 - x2) es distinto del vector 0.
# En otras palabras, existirian vectores "d" distintos de cero tales que
#                       A d = 0
# Si d es solucion de la ecuacion "homogenea", lambda*d, donde lambda es cualquier
# numero real, tambien lo es.
# Que significado geometrico tiene d?
# Las componentes de d son incognita, llamemoslas d1, d2 y d3.
#                        A d = d1*c1A + d2*c2A + d3* c3A = 0
# es decir, A d es una combinacion lineal de los vectores columna de A que da como resultado
# el vector 0.
# Pero que exista tal combinacion lineal (no todos cero) implica que, por ejemplo
# (si d3 es distinto de cero):
#                    c3A = -(d1/d3)*c1A - (d2/d3)*c2A 
# es decir, que la tercera columna sea combinacion linal de las primeras dos.
# Es decir, implica que los vectores columna no son linealmente independientes. 
# 
# Esto implica que 
#                 (d1/d3)*c1A + (d2/d3)*c2A + c3A = 0

In [22]:
# recuerden que en una de las primeras celdas, construimos la columna c3 de A asi:
# d1 = 2*(np.random.rand()-0.5) 
# d2 = 2*(np.random.rand()-0.5)
# c3 = d1*c1 + d2*c2  # c3, por construccion, es linealmente dependiente de c1 y c2.
# Esto significa que el vector
x_0 = np.array([[d1],[d2],[-1]])
print(x_0)
# tiene que ser solucion de la ecuacion homogenea A x = 0. Probemos:
np.dot(A,x_0)

[[-0.68698789]
 [-0.47817713]
 [-1.        ]]


array([[0.],
       [0.],
       [0.]])

In [23]:
# Entonces x_0 multiplicado por cualquier escalar tambien tiene que ser solucion:
lambd = 20*(np.random.rand()-0.5) # numero aleatorio entre -10 y 10
x_01 = lambd*x_0 # ojo que la palabra lambda esta protegida
np.dot(A,x_01)

array([[0.],
       [0.],
       [0.]])

In [24]:
# Por lo tanto la solucion general de A x = b es una solucion particular x mas 
# una solucion cualquiera de la ecuacion A x = 0 (que llamamos x_01 = lambd*x_0):
print(np.dot(A,x + x_01) - b)

[[ 2.55351296e-15]
 [-1.33226763e-15]
 [ 1.77635684e-15]]


In [ ]:
# Notar que en este caso la matriz A fue construida a proposito de modo que
# conocemos como construir la solucion de A x = 0.
# En casos realistas esto no es asi. La semana que viene aprenderemos a resolverla
# en general.

## HW2

1- Por que, cuando intentamos resolver la ecuacion que no tenia solucion, la manera que encontro Python 
de decirnos que no habia solicion es darnos una supesta solucion consistente en un vector de
magnitud gigante?

2- Generamos una matriz de $A: m \times n$ and azar y un vector $\mathbf{y}: m \times 1$.

In [31]:
m = 3
n = 2
A = 2*(np.random.rand(m,n)-0.5)
y = 2*(np.random.rand(m,1)-0.5)
print("A = \n", A)
print("y = \n", y)

A = 
 [[ 0.05709554  0.99691885]
 [ 0.27450591 -0.58283894]
 [-0.84092477  0.30829901]]
y = 
 [[-0.72463693]
 [-0.34699863]
 [-0.23225261]]


Tratar de resolver la ecuacion $A \mathbf{x} = \mathbf{y}$, con x = LA.solve(A, y), para diferentes valores de m y n.
Comprobar numericamente que:

Si $m > n$, el sistema no tiene solución.

Si $m < n$, el sistema tiene infinitas soluciones (construir las infinitas soluciones como hicimos mas arriba).

Si $m = n$, hay una única solución.

Encontrar la manera (analiticamente, reproduciendo el argumento dado en clase, pero ademas numericamente con Python) de verificar que$$\dim C(A) + \dim N(A) = n$$

In [25]:
'''Autovalores y Autovectores'''

'Autovalores y Autovectores'

In [48]:
n=100
A = np.random.randn(n,n)
print(A)

[[-0.37821604 -1.00836823  1.11211033 ... -0.69813001 -0.1336059
  -0.25174001]
 [ 0.11120479  1.5762068  -0.10888885 ... -0.21492715  2.19325269
  -0.47392529]
 [-0.27374387  0.17137625 -0.53363463 ...  2.06882993 -1.33490763
   0.77352996]
 ...
 [ 0.70015678 -0.14154099  0.11439602 ... -1.18355242  0.37183968
  -0.16435918]
 [ 0.86447523  1.46153835 -0.48739029 ...  0.03121905  0.82422284
  -0.30835769]
 [ 0.4395312   0.14769686  0.5967996  ...  1.19769504  0.15106102
  -0.55037316]]


In [49]:
w, v = LA.eig(A) # ver https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html
print(w.shape)
print(v.shape)
print("w = ", w) # w es (2,) ((n,) en general), y cada componente es un autovalor de A LEER que significa (2,)
print("v = \n",v) # v es (2,2) ((n,n) en general), y cada columna es un autovector de A

(100,)
(100, 100)
w =  [-6.89036755+7.81158535j -6.89036755-7.81158535j -7.9011511 +6.27996237j
 -7.9011511 -6.27996237j  8.46217647+4.33555251j  8.46217647-4.33555251j
 -9.90704549+1.64253662j -9.90704549-1.64253662j -4.93929737+8.19154975j
 -4.93929737-8.19154975j  8.83486619+0.51946244j  8.83486619-0.51946244j
 -0.18897299+9.50066535j -0.18897299-9.50066535j  8.42176475+0.j
  4.08063883+8.08792006j  4.08063883-8.08792006j  5.15529074+7.04384881j
  5.15529074-7.04384881j  2.91438084+8.40622461j  2.91438084-8.40622461j
 -2.80769933+8.75053049j -2.80769933-8.75053049j  1.33407535+8.81507741j
  1.33407535-8.81507741j  7.30198516+3.90702343j  7.30198516-3.90702343j
  6.48102137+5.18151854j  6.48102137-5.18151854j -8.22343848+3.76991344j
 -8.22343848-3.76991344j -8.38754725+2.35910763j -8.38754725-2.35910763j
 -8.81070038+0.j          4.49056191+6.06245881j  4.49056191-6.06245881j
  6.98520894+1.27630184j  6.98520894-1.27630184j  6.71932501+2.24545057j
  6.71932501-2.24545057j -2.46236166

In [38]:
AutoV1_A = v[:, [0]]
AutoV2_A = v[:, [1]]
print(AutoV1_A)
print(LA.norm(AutoV1_A))
print(AutoV2_A)
print(LA.norm(AutoV2_A))
print(np.dot(A,AutoV1_A)/AutoV1_A) # comprobamos que AutoV1_A es un autovector de A
                                   # con autovalor w[0]. (division por vector es comp. a comp.)
print(np.dot(A,AutoV2_A)/AutoV2_A) 

[[-0.74081473]
 [ 0.67170941]]
0.9999999999999999
[[-0.38922095]
 [-0.92114443]]
0.9999999999999999
[[-2.91181238]
 [-2.91181238]]
[[0.17965362]
 [0.17965362]]


In [39]:
# Comprovar visualmente en Geogebra que no son en general ortogonales
print(np.dot(np.transpose(AutoV1_A),AutoV2_A))

[[-0.33040077]]


In [50]:
# A = (A + A^T)/2 + (A - A^T)/2, (A + A^T)/2 es simetrica, (A - A^T)/2 antisimetrica
As = (A + np.transpose(A))/2
print(As)

[[-3.78216035e-01 -4.48581721e-01  4.19183232e-01 ...  1.01338678e-03
   3.65434666e-01  9.38955923e-02]
 [-4.48581721e-01  1.57620680e+00  3.12437016e-02 ... -1.78234072e-01
   1.82739552e+00 -1.63114215e-01]
 [ 4.19183232e-01  3.12437016e-02 -5.33634631e-01 ...  1.09161297e+00
  -9.11148962e-01  6.85164780e-01]
 ...
 [ 1.01338678e-03 -1.78234072e-01  1.09161297e+00 ... -1.18355242e+00
   2.01529367e-01  5.16667927e-01]
 [ 3.65434666e-01  1.82739552e+00 -9.11148962e-01 ...  2.01529367e-01
   8.24222835e-01 -7.86483317e-02]
 [ 9.38955923e-02 -1.63114215e-01  6.85164780e-01 ...  5.16667927e-01
  -7.86483317e-02 -5.50373158e-01]]


In [51]:
ws, vs = LA.eig(As) 
print(ws) 
print(vs)

[-14.31579688  13.31371423 -13.25216422 -12.71227107  12.50145794
  11.96748364  11.67497359 -12.17413918 -11.94350037 -11.66977862
  11.39243805  11.04551339  10.64049593  10.1962359    9.98422348
   9.87365919 -11.12171265 -10.91368568 -10.71482665 -10.48615919
 -10.27563298  -9.54216456  -9.3987075   -9.64871625   9.01698316
   8.94559493   8.67794278   8.51467475  -9.06063275   8.16818208
   7.98301781  -8.71116302  -8.4198165    7.55563853  -8.28454581
  -7.99171849   7.35602014   6.97851745   6.91402451   6.82876389
  -7.7213453   -7.47485912  -7.20544235   6.29984384   5.85084989
   5.77707071  -6.80580209  -6.6121799   -6.45715005  -6.22824361
   5.38720493  -5.9261272    5.00871261   5.13940125   4.68120566
   4.63047715  -5.47445508   4.32379902   4.41062085  -5.23090615
  -5.03827753  -4.73876929   3.80909792  -4.63161471   3.67955948
  -4.25707743  -3.89751346  -3.7935144    3.28824619   2.99440347
   2.91287431   2.67856796   2.3197248   -3.49484992  -3.40211912
   3.52625

In [52]:
AutoV1_As = vs[:, [53]]
AutoV2_As = vs[:, [65]]
print(AutoV1_As)
print(AutoV2_As)
print(np.dot(np.transpose(AutoV1_As),AutoV2_As)) # Los autovectores de una matriz simetrica
                                                 # son ortogonales entre si

[[-2.61222200e-04]
 [ 1.62595124e-01]
 [-1.16353840e-01]
 [ 2.25075621e-02]
 [ 9.85377767e-02]
 [-7.70727694e-03]
 [ 1.68940186e-01]
 [ 6.41597364e-02]
 [-3.99022336e-02]
 [ 1.63069047e-01]
 [-2.97595801e-01]
 [ 8.69976146e-02]
 [-1.57801901e-02]
 [ 7.89879696e-02]
 [-1.33948139e-01]
 [-3.01653662e-02]
 [ 4.76421288e-02]
 [-4.24010053e-02]
 [-9.04850006e-02]
 [-4.95431084e-02]
 [-9.36915030e-02]
 [-7.07586037e-02]
 [ 1.82411365e-02]
 [-2.00245116e-01]
 [-1.45486570e-02]
 [ 8.91818342e-03]
 [-1.23927818e-01]
 [-1.16970342e-01]
 [-6.68287199e-02]
 [-1.10382439e-02]
 [-5.18353462e-02]
 [ 4.61862252e-02]
 [-1.87409454e-01]
 [-1.02304626e-01]
 [-4.82162456e-02]
 [-3.88759055e-02]
 [-3.08803091e-02]
 [ 5.53935089e-02]
 [ 5.16990861e-02]
 [-2.02838729e-02]
 [ 1.57100223e-01]
 [ 9.94641127e-02]
 [-1.64257686e-01]
 [-9.72943665e-02]
 [-2.06541556e-01]
 [ 9.75521398e-04]
 [ 4.83660262e-02]
 [ 7.11101713e-02]
 [-7.67672429e-02]
 [ 1.86407122e-01]
 [ 1.07961553e-01]
 [ 8.73477370e-02]
 [-5.1016856

In [ ]:
"""Entender lo hecho en este JN y visualizar todo en Geogebra (o si pueden en Python Spyder 3-D).
Cuando el sisema de ecuaciones tiene una unica solucion, cuando tiene muchas, etc."""