In [5]:
import numpy as np
from numpy import linalg as LA  # Notar que importamos linalg con nickname LA

In [6]:
C = np.array([[1,1],[1,0]])
print(C)

[[1 1]
 [1 0]]


In [7]:
w, v = LA.eig(C) 
print(w) 
print(v) 

[ 1.61803399 -0.61803399]
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [8]:
AutoV1_C = v[:, [0]]
AutoV2_C = v[:, [1]]
print(AutoV1_C)
print(AutoV2_C)

[[0.85065081]
 [0.52573111]]
[[-0.52573111]
 [ 0.85065081]]


In [9]:
# Generamos una matriz A de nxn (n=2 originalmente) al azar y su traspuesta
n = 4
A = 2*(np.random.rand(n,n)-0.5)  #
AT=A.T
print(A)
print(AT)

[[-0.08724221  0.22529518 -0.47396727  0.2813713 ]
 [-0.09901549 -0.94496879  0.65211635 -0.69101699]
 [ 0.80379361 -0.57848534  0.85440773  0.60019601]
 [ 0.94137448 -0.2967499   0.0744565   0.31870652]]
[[-0.08724221 -0.09901549  0.80379361  0.94137448]
 [ 0.22529518 -0.94496879 -0.57848534 -0.2967499 ]
 [-0.47396727  0.65211635  0.85440773  0.0744565 ]
 [ 0.2813713  -0.69101699  0.60019601  0.31870652]]


In [10]:
# Calculamos sus autovectores y autovalores (notar que en general son complejos)
wA, vA = LA.eig(A)
print("autovalores de A =",wA) 
print("autovectores de A =\n",vA) 
wAT, vAT = LA.eig(AT)
print("autovalores de AT =",wAT) 
print(vAT) 

autovalores de A = [ 0.70667116+0.65367699j  0.70667116-0.65367699j -0.28504985+0.j
 -0.98738923+0.j        ]
autovectores de A =
 [[-0.1878693 +0.2203563j  -0.1878693 -0.2203563j   0.50439628+0.j
  -0.18905861+0.j        ]
 [ 0.15674332-0.22973158j  0.15674332+0.22973158j  0.67166325+0.j
   0.89072301+0.j        ]
 [ 0.81330332+0.j          0.81330332-0.j          0.24121668+0.j
   0.25668751+0.j        ]
 [ 0.20247922+0.36924658j  0.20247922-0.36924658j -0.48607344+0.j
   0.32400754+0.j        ]]
autovalores de AT = [ 0.70667116+0.65367699j  0.70667116-0.65367699j -0.98738923+0.j
 -0.28504985+0.j        ]
[[-0.64875947+0.j         -0.64875947-0.j          0.22846307+0.j
  -0.86516766+0.j        ]
 [ 0.05985788+0.1476128j   0.05985788-0.1476128j  -0.70927985+0.j
  -0.24580483+0.j        ]
 [ 0.03678484-0.47324897j  0.03678484+0.47324897j  0.33327516+0.j
  -0.24294335+0.j        ]
 [-0.57224769-0.03087898j -0.57224769+0.03087898j -0.57762825+0.j
   0.36337781+0.j        ]]


In [11]:
# Tomamos la parte simetrica de A: A = (A + AT)/2 + (A - AT)/2 = A_sim + A_antisim
A_sim = (A + AT)/2
A_sim

array([[-0.08724221,  0.06313985,  0.16491317,  0.61137289],
       [ 0.06313985, -0.94496879,  0.0368155 , -0.49388344],
       [ 0.16491317,  0.0368155 ,  0.85440773,  0.33732626],
       [ 0.61137289, -0.49388344,  0.33732626,  0.31870652]])

In [12]:
# calculamos los autovalores, que son reales y los autovectores (ortogonales)
wA_sim, vA_sim = LA.eig(A_sim)
print(wA_sim) 
print(vA_sim)

[-1.195683   -0.36312344  1.20635924  0.49335045]
[[ 0.26402755 -0.80597059  0.36213738  0.38672649]
 [-0.87323978 -0.43108683 -0.11117623 -0.19813198]
 [ 0.06107947  0.00983949  0.7178714  -0.69342133]
 [-0.40498277  0.40555977  0.58408648  0.57476361]]


In [17]:
AutoV0_A = vA_sim[:, [0]]
AutoV1_A = vA_sim[:, [1]]
AutoV2_A = vA_sim[:, [2]]
AutoV3_A = vA_sim[:, [3]]

print(np.dot(AutoV1_A.T,AutoV3_A))

[[4.4408921e-16]]


# Trabajo practico

1) Comprobar que los autovectores son ortonormales.

2) Generar un vector $\mathbf{x} \in \mathbb{R}^{n \times 1}$ al azar, donde $n$ es el mismo $n$ de la matriz simetrica $A_{sim}$ generada unas celdas mas arriba. Si llamamos $\hat{\mathbf{a}}_i, i = 1, \ldots, n$, a los autovectores ortonormales de $A_{sim}$, $A_{sim} \mathbf{a} = \lambda_i \mathbf{a}$, donde $\lambda_i$ es el correspondiente autovector (real), entonces comprobar que$$
\mathbf{x} = \sum_{i=1}^n (\mathbf{a}_i^{\top}\mathbf{x}) \mathbf{a}_i$$
Por lo tanto $\mathbf{a}_i^{\top}\mathbf{x}$ es la coordenada i-esima de $\mathbf{x}$ en la base de autovectores de $A_{sim}$.
Generar en vector cuyas coordenadas en la base canonica son $\mathbf{a}_i^{\top}\mathbf{x}$, $$
\left(
  \begin{array}{c}
    \mathbf{a}_0^{\top}\mathbf{x} \\
    \mathbf{a}_1^{\top}\mathbf{x} \\
    \mathbf{a}_2^{\top}\mathbf{x} \\
    \mathbf{a}_3^{\top}\mathbf{x} \\
  \end{array}
\right)
$$

3) Construir, para n = 2, la forma cuadratica $f(x)=x^T A_{sim} x$, donde $x = (x_1, x_2)$, es un vector de $\mathbb{R}^2$. Graficarla en 3-d en Python y Geogebra.

4) Construir ejes asociados a los autovectores. Comprobar visualmente que son ortogonales.

Borrar (en geogebra y Python) los ejes originales y quedarse solo con los ejes correspondiente a los autovectores.

Comparar con la superficie del archivo Geogebra "FormasCuadraticas", donde explcitamente la forma cuadratica no tiene terminos cruzados.

Girar el grafico de modo que convenserse visualmente que en esos ejes la superficie no tiene terminos cruzados.

Que rol juegan los autovalores de A_sim en la forma de la superficie?

Nuevamente comparar con el archivo Geogebra "FormasCuadraticas"

4) Analiticamente mostrar que si parto de una forma cuadratica en $n$ variables:$$
    f(x_1,...,x_n) = \sum_{i = 1}^n a_i x_i^2 + \sum_{j < i, i = 2}^n a_{ij} x_i x_j = \mathbf{x}^{\top} A \mathbf{x}, \quad \text{donde} \quad \mathbf{x} = \left(
                                                             \begin{array}{c}
                                                               x_1 \\
                                                               \vdots \\
                                                               x_n \\
                                                             \end{array}
                                                           \right)$$
    y $A \in \mathbb{R}^{n \times n}$ es una matriz simetrica con elementos diagonales dados por $a_i$ y no diagonales dados por $a_{ij}/2$.

5) Supongamos que al vector genérico $\mathbf{x}$ lo expreso como una combinacion lineal de los $n$ autovectores 
ortonormalizados de $A$, esto es,$$
\mathbf{x} = \sum_{i=1}^n b_i \hat{\mathbf{a}}_i, \quad \text{con} \quad A \hat{\mathbf{a}}_i = \lambda_i \hat{\mathbf{a}}_i,
\quad \hat{\mathbf{a}}_i \cdot \hat{\mathbf{a}}_j = \delta_{ij}$$
donde $b_i$ es la coordenada $i-$esima del vector $x$ en la base $\{ \hat{\mathbf{a}}_i \}$ (ver punto 2) y $\lambda_i$
es el $i-$esimo autovalor de $A$. Mostrar que$$
\mathbf{x}^{\top} A \mathbf{x} = \sum_{i=1}^n \lambda_i b_i^2$$
Es decir que la forma cuadrática $f$, expresada en las coordenadas correspondientes a la base de autovectres de $A$,
no tiene términos cruzados! 

6) En base a lo probado en el punto anterior, explicar de que depende que el origen $\mathbf{x} = \mathbf{0}$ sea un maximo, un minimo, o una silla de montar. 

Llamemos U = vA_sim y comprobemos que es una matriz ortogonal, que U.T tambien lo es, y que U(U.T) = (U.T)U=I

In [20]:
U = vA_sim
UT = U.T
np.dot(UT,U)

array([[ 1.00000000e+00,  2.49800181e-16, -5.55111512e-17,
        -9.71445147e-17],
       [ 2.49800181e-16,  1.00000000e+00,  2.22044605e-16,
         4.44089210e-16],
       [-5.55111512e-17,  2.22044605e-16,  1.00000000e+00,
         2.22044605e-16],
       [-9.71445147e-17,  4.44089210e-16,  2.22044605e-16,
         1.00000000e+00]])

In [27]:
# Extraemos columnas y filas de U, notar las shapes
print(U)
print(U[:, [2]])
print(U[:, [2]].shape)
print(U[[2],:])
print(U[[2],:].shape)

[[ 0.26402755 -0.80597059  0.36213738  0.38672649]
 [-0.87323978 -0.43108683 -0.11117623 -0.19813198]
 [ 0.06107947  0.00983949  0.7178714  -0.69342133]
 [-0.40498277  0.40555977  0.58408648  0.57476361]]
[[ 0.36213738]
 [-0.11117623]
 [ 0.7178714 ]
 [ 0.58408648]]
(4, 1)
[[ 0.06107947  0.00983949  0.7178714  -0.69342133]]
(1, 4)


In [34]:
# comprobamos que tanto las columnas como las filas de U son ortonormales
print(np.dot(U[:, [2]].T,U[:, [0]])) # las columnas son ortonormales
print(np.dot(U[[2],:],U[[2],:].T)) # las fias son ortonormales

[[-2.77555756e-17]]
[[1.]]


In [36]:
print(np.dot(U.T,np.dot(A_sim,U)))
print(wA_sim)

[[-1.19568300e+00 -3.46944695e-16  1.11022302e-16  4.51028104e-17]
 [-3.88578059e-16 -3.63123437e-01  4.99600361e-16  1.11022302e-16]
 [ 1.66533454e-16  4.30211422e-16  1.20635924e+00  4.16333634e-16]
 [ 9.71445147e-17  9.71445147e-17  3.33066907e-16  4.93350447e-01]]
[-1.195683   -0.36312344  1.20635924  0.49335045]


Comprobar que:

7) Con el mismo vector $\mathbf{x}$ de la parte 2), comprobar que $U^{\top} \mathbf{x}$ es el mismo vector generado en 2), es decir el vector cuyas coordenadas en la base canonica son las coordenadas de $\mathbf{x}$ en la base de autovectores de $A$.

8) Comprobar que $\mathbf{x}^{\top}U$ es el traspuesto del calculado en 7). 

9) Comprobar que $U^{\top}AU$ es una matriz diagonal cuyos elementos diagonales son los autovalores de $A_{sim}$.