In [1]:
import numpy as np
from numpy import linalg as LA


import scipy
from scipy import linalg
from scipy import stats

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

from sklearn.utils.extmath import randomized_svd # esta funcion vamos a usar

In [2]:
n=3
M = np.random.randn(n,n)
M

array([[-1.92090359,  1.94043523, -0.21528529],
       [-0.54848798, -0.09936518,  0.91625954],
       [ 0.80020669, -1.27768637, -2.32075618]])

In [3]:
# A es la parte simetrica de M
A = (M.T + M)/2
A

array([[-1.92090359,  0.69597362,  0.2924607 ],
       [ 0.69597362, -0.09936518, -0.18071341],
       [ 0.2924607 , -0.18071341, -2.32075618]])

In [4]:
w,v = LA.eigh(A)
print("autovalores = ", w)
print("autovectores = \n", v)

autovalores =  [-2.58482197 -1.89480302  0.13860003]
autovectores = 
 [[ 0.57608733 -0.75388304 -0.31588566]
 [-0.21858159  0.23029785 -0.94825365]
 [-0.78762014 -0.6153237   0.03211329]]


In [6]:
U, d, VT = randomized_svd(A, n_components = 2, random_state=0)
print("U = \n", U)
print("d = \n", d)
print("VT = \n", VT)

U = 
 [[-0.57608733  0.75388304]
 [ 0.21858159 -0.23029785]
 [ 0.78762014  0.6153237 ]]
d = 
 [2.58482197 1.89480302]
VT = 
 [[ 0.57608733 -0.21858159 -0.78762014]
 [-0.75388304  0.23029785 -0.6153237 ]]


In [7]:
D = np.diag(d)
D

array([[2.58482197, 0.        ],
       [0.        , 1.89480302]])

In [8]:
AA = np.dot(U, np.dot(D,VT))
Error = A - AA
print("AA = \n", AA)
print("A = \n", A)
print("Error = \n", Error)

AA = 
 [[-1.93473362  0.65445741  0.29386668]
 [ 0.65445741 -0.22399225 -0.17649283]
 [ 0.29386668 -0.17649283 -2.32089912]]
A = 
 [[-1.92090359  0.69597362  0.2924607 ]
 [ 0.69597362 -0.09936518 -0.18071341]
 [ 0.2924607  -0.18071341 -2.32075618]]
Error = 
 [[ 0.01383003  0.04151622 -0.00140598]
 [ 0.04151622  0.12462707 -0.00422058]
 [-0.00140598 -0.00422058  0.00014293]]
